[build]
  publish = "public"
  functions = "netlify/functions"
  command = "npm run build"

[build.environment]
  PYTHON_VERSION = "3.9"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/v2/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/calculator"
  to = "/calculative/index.html"
  status = 200

[[redirects]]
  from = "/app"
  to = "/calculative/index.html"
  status = 200

[[redirects]]
  from = "/about"
  to = "/about.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  python_runtime = "python3.9"
